---
title: "QRMon experiments"
author: "Anton Antonov"
date: "1/19/2019"
output: html_notebook
---

```{r}
library(magrittr)
library(ggplot2)
library(quantreg)
library(splines)
#library(QRMon)
devtools::load_all()
```

# Introduction

# Data

```{r}
data(airquality)
summary(airquality)
```

```{r}
library(MASS)
data(mcycle)
summary(mcycle)
```

# Main pipeline

## Orlando temperature data

```{r}
devtools::load_all()
```

```{r}
qrmon <-
  QRMonUnit( dfTemperatureData ) %>%
  QRMonRescale(TRUE, TRUE) %>% 
  QRMonQuantileRegression( df = 12, degree = 3, fractions = 1:9/10 ) %>% 
  QRMonPlot( dataPointsColor = "gray50", regressionCurvesColor = ~ RegressionCurve )
```

```{r}
qrmon %>% QRMonSeparateToFractions() %>% QRMonTakeValue()
```


## MASS dataset

(Using this dataset here because it is used in [the vignette](https://cran.r-project.org/web/packages/quantreg/vignettes/rq.pdf) 
of the package ["quantreg"](https://cran.r-project.org/web/packages/quantreg/index.html).)

```{r}
qrmon <-
  QRMonUnit( mcycle ) %>%
  QRMonQuantileRegression( df = 12, degree = 3, fractions = seq(0.2,0.8,0.2) ) %>% 
  QRMonPlot( dataPointsColor = "gray10", regressionCurvesColor = ~ RegressionCurve )
```

## Fractions

```{r}
qrmon %>% QRMonSeparateToFractions() %>% QRMonTakeValue()
```

# Conditional CDF's

```{r}
qrmon <-
  QRMonUnit( dfDistributionData ) %>% 
  QRMonQuantileRegression( df = 6, degree = 3, fractions = 1:9/10 ) %>% 
  QRMonPlot()
```

```{r}
resCDFs <-
  qrmon %>% 
  QRMonConditionalCDF( timePoints = c(-2,0) ) %>% 
  QRMonTakeValue()
```

```{r}
plotDF <- 
  purrr::map_df( names(resCDFs), 
                 function(timePoint) {
                   xs <- qrmon %>% QRMonPredict( newdata = as.numeric(timePoint) ) %>% QRMonTakeValue()
                   xs <- purrr::map_dbl(xs, function(x) x$Value)
                   cbind( Time = timePoint, 
                          purrr::map_df( xs, function(x) data.frame( Value = x, CDF = resCDFs[[timePoint]](x) ) ),
                          stringsAsFactors = FALSE)
                 } )
```

```{r}
ggplot(plotDF) +
  geom_line( aes(x = Value, y = CDF) ) +
  facet_wrap( ~Time, scales = "free")
```


# Outliers


```{r}
qrmon <-
  QRMonUnit( dfTemperatureData ) %>% 
  QRMonSetRegressionObjects(NULL) %>% 
  QRMonQuantileRegression( df = 16, fractions = c(0.02,0.98) ) %>% 
  QRMonOutliers() %>% 
  QRMonOutliersPlot( plotRegressionCurvesQ = TRUE )
```

# Errors

```{r}
data.189185 <-
  data.frame( 
    X = c(1387.5, 1302.5, 1222.5, 1182.5, 1142.5, 1097.5, 852.5, 897.5, 977.5,
          937.5, 812.5, 732.5, 652.5, 692.5, 567.5, 527.5, 447.5, 362.5, 322.5,
          282.5, 242.5, 202.5, 157.5, 1017.9, 77.5),
    Y = c( 266500., 263500., 245500., 238500., 231500., 230500., 224500., 
           224500., 222500., 220500., 217500., 195500., 183500., 183500., 
           176500., 172500., 162500., 145500., 127500., 109500., 93500., 71500., 
           48500., 47970.2, 15500.)
  )
```


```{r}
res <-
  QRMonUnit( data.189185 ) %>%
  QRMonQuantileRegression( df = 12, degree = 3, fractions = 0.5 ) %>% 
  QRMonQuantileRegression( df = 3, degree = 2, fractions = 0.55 ) %>% 
  QRMonPlot() %>% 
  QRMonErrorsPlot() %>% 
  QRMonTakeValue()
```

# Pick points

```{r}
qrmon <-
  QRMonUnit( mcycle) %>%
  QRMonQuantileRegression( df = 12, degree = 3, fractions = 0.5 ) %>% 
  QRMonPlot( dataPointsColor = "gray50", regressionCurvesColor = ~ RegressionCurve ) %>% 
  QRMonErrorsPlot() %>% 
  QRMonPickPathPoints( threshold = 10, pickAboveThresholdQ = FALSE )
```

```{r}
ggplot( (qrmon %>% QRMonTakeValue())[[1]] ) +
  geom_point( aes( x = Time, y = Value ) )
```



# Simulate

```{r}
qrmon <-
  QRMonUnit( dfTemperatureData ) %>% 
  QRMonEchoDataSummary() %>% 
  QRMonSetRegressionObjects(NULL) %>% 
  QRMonQuantileRegression( df = 16, fractions = c(0.01, 1:7/8, 0.99) ) %>% 
  QRMonPlot(dataPointsColor = "gray70")
```

```{r}
qrmon <- qrmon %>% QRMonSimulate(1000)
qDF <- rbind( cbind( Type = "Original", qrmon %>% QRMonTakeData() ),
              cbind( Type = "Simulated", as.data.frame( qrmon %>% QRMonTakeValue() )))
ggplot( qDF ) +
  geom_line( aes( x = Time, y = Value ), color = "lightblue" ) +
  facet_wrap( ~Type, ncol=1)
```

# Using formulas

```{r}
qrMon <- 
  QRMonUnit( dfDistributionData ) %>% 
  QRMonQuantileRegressionFit( formula = Value ~ cos(Time) + cos(2*Time) + Time^3, fractions = 0.5 ) %>% 
  QRMonPlot
```

```{r}
qrMon %>% QRMonPredict( c(0, 0.5, 2) ) %>% QRMonTakeValue
```

